apiVersion: apps/v1
kind: Deployment
metadata:
  name: tensorflow-serving
spec:
  replicas: 4 # TODO change to 12
  selector:
    matchLabels:
      app: tensorflow-serving
  template:
    metadata:
      labels:
        app: tensorflow-serving
    spec:
      containers:
      - command:
        - /usr/bin/tf_serving_entrypoint.sh
        - --model_config_file=/models/konohana.config
        name: tensorflow-serving
        image: 10.11.0.10:5000/predict-konohana-pc
        ports:
        - containerPort: 8500
      nodeSelector:
        kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: tensorflow-service
spec:
  ports:
  - port: 8500
    targetPort: 8500
  selector:
    app: tensorflow-serving
  type: ClusterIP
