apiVersion: wao.bitmedia.co.jp/v1beta1
kind: NodeConfigTemplate
metadata:
  name: nodes
  namespace: wao-system
spec:
  nodeSelector:
    matchLabels:
      hoge: fuga
  template:
    nodeName: ""
    metricsCollector:
      inletTemp:
        type: Fake
        endpoint: ""
        fetchInterval: 10s
      deltaP:
        type: Fake
        endpoint: ""
        fetchInterval: 10s
    predictor:
      powerConsumption:
        type: Fake
        endpoint: ""
        fetchInterval: 10s
