apiVersion: v1
kind: ConfigMap
metadata:
  name: wao-scheduler-config
  namespace: kube-system
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
      - schedulerName: wao-scheduler
        plugins:
          multiPoint:
            enabled:
            - name: MinimizePower
              weight: 20
            - name: PodSpread
        pluginConfig:
          - name: MinimizePower
            args:
              metricsCacheTTL: 15s
              predictorCacheTTL: 15m
              podUsageAssumption: 0.8
              cpuUsageFormat: Percent
