apiVersion: v1
kind: Service
metadata:
  name: nginx-waolb
  labels:
    service.kubernetes.io/service-proxy-name: wao-loadbalancer
  annotations:
    waok8s.github.io/cpu-per-request: "500m" # CPU per request
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
