apiVersion: v1
kind: Service
metadata:
  name: nginx-waolb
  labels:
    app: nginx
    service.kubernetes.io/service-proxy-name: wao-loadbalancer
  annotations:
    waok8s.github.io/cpu-per-request: "500m" # CPU per request (not yet implemented)
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx
