apiVersion: v1
kind: ServiceAccount
metadata:
  name: wao-scheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custom-metrics-server-resources
rules:
- apiGroups:
  - custom.metrics.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metrics-reader
rules:
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  - nodes
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wao-scheduler-extension-apiserver-authentication-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: wao-scheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wao-scheduler-as-secret-reader
  namespace: wao-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-reader
subjects:
- kind: ServiceAccount
  name: wao-scheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wao-scheduler-as-custom-metrics-server-resources
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: custom-metrics-server-resources
subjects:
- kind: ServiceAccount
  name: wao-scheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wao-scheduler-as-kube-scheduler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kube-scheduler
subjects:
- kind: ServiceAccount
  name: wao-scheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wao-scheduler-as-metrics-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metrics-reader
subjects:
- kind: ServiceAccount
  name: wao-scheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wao-scheduler-as-volume-scheduler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:volume-scheduler
subjects:
- kind: ServiceAccount
  name: wao-scheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wao-scheduler-as-wao-nodeconfig-viewer-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wao-nodeconfig-viewer-role
subjects:
- kind: ServiceAccount
  name: wao-scheduler
  namespace: kube-system
---
apiVersion: v1
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
      - schedulerName: wao-scheduler
        plugins:
          multiPoint:
            enabled:
            - name: MinimizePower
              weight: 20
            - name: PodSpread
        pluginConfig:
          - name: MinimizePower
            args:
              metricsCacheTTL: 15s
              predictorCacheTTL: 15m
              podUsageAssumption: 0.8
              cpuUsageFormat: Percent
kind: ConfigMap
metadata:
  name: wao-scheduler-config
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wao-scheduler
    component: scheduler
    tier: control-plane
  name: wao-scheduler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wao-scheduler
      component: scheduler
      tier: control-plane
  template:
    metadata:
      labels:
        app: wao-scheduler
        component: scheduler
        tier: control-plane
    spec:
      containers:
      - command:
        - kube-scheduler
        - --v=5
        - --config=/etc/kubernetes/wao-scheduler/scheduler-config.yaml
        image: ghcr.io/waok8s/wao-scheduler:v1.30.0
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10259
            scheme: HTTPS
          initialDelaySeconds: 15
        name: wao-scheduler
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10259
            scheme: HTTPS
        resources:
          requests:
            cpu: 100m
        securityContext:
          privileged: false
        volumeMounts:
        - mountPath: /etc/kubernetes/wao-scheduler
          name: config-volume
      hostNetwork: false
      hostPID: false
      serviceAccountName: wao-scheduler
      volumes:
      - configMap:
          name: wao-scheduler-config
        name: config-volume
