name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # git fetch --unshallow
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: "test: unit tests"
        run: make test
      - name: "test: integration tests"
        run: ./test/reset-cluster.sh && ./test/run-tests.sh
      - uses: codecov/codecov-action@v3
