apiVersion: v1
kind: Service
metadata:
  name: wao-metrics-adapter
  namespace: custom-metrics
spec:
  ports:
    - name: https
      port: 443
      targetPort: 6443
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: wao-metrics-adapter
