name: CI
on:
  push:
    branches: [main, release-*]
  pull_request:
    branches: [main, release-*]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # git fetch --unshallow
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: "test: unit tests"
        run: make test
      - name: "test: deploy"
        run: ./hack/dev-kind-reset-cluster.sh && ./hack/dev-kind-deploy-second-proxy.sh
      # - name: "test: integration tests"
      #   run: ./test/reset-test-cluster.sh && ./test/run-tests.sh
