// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package api

// InternalError defines model for InternalError.
type InternalError struct {
	Error *struct {
		MessageExtendedInfo *struct {
			// Message error message
			Message *string `json:"Message,omitempty"`
		} `json:"@Message.ExtendedInfo,omitempty"`

		// Code message code
		Code *string `json:"code,omitempty"`

		// Message error message
		Message *string `json:"message,omitempty"`
	} `json:"error,omitempty"`
}

// MachineLearningModel defines model for MachineLearningModel.
type MachineLearningModel struct {
	// OdataContext Context URL of resource
	OdataContext *string `json:"@odata.context,omitempty"`

	// OdataId ID of resource
	OdataId *string `json:"@odata.id,omitempty"`

	// OdataType Type of resource
	OdataType *string `json:"@odata.type,omitempty"`

	// Name Resource name
	Name                  *string `json:"Name,omitempty"`
	PowerConsumptionModel *struct {
		// Name Name of power consumption model
		Name *string `json:"Name,omitempty"`

		// Url URL of power consumption model
		Url *string `json:"Url,omitempty"`
	} `json:"PowerConsumptionModel,omitempty"`
	ResponseTimeModel *struct {
		// Name Name of response time model
		Name *string `json:"Name,omitempty"`

		// Url URL of response time model
		Url *string `json:"Url,omitempty"`
	} `json:"ResponseTimeModel,omitempty"`
}

// System defines model for System.
type System struct {
	MachineLearningModel *struct {
		// OdataId Path of the machine learning model resource
		OdataId *string `json:"@odata.id,omitempty"`
	} `json:"MachineLearningModel,omitempty"`
}
