# permissions for end users to view nodeconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: wao-core
    app.kubernetes.io/managed-by: kustomize
  name: node-nodeconfig-viewer-role
rules:
- apiGroups:
  - node.waok8s.github.io
  resources:
  - nodeconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - node.waok8s.github.io
  resources:
  - nodeconfigs/status
  verbs:
  - get
