---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - node.waok8s.github.io
  resources:
  - nodeconfigs
  - nodeconfigtemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - node.waok8s.github.io
  resources:
  - nodeconfigs/finalizers
  - nodeconfigtemplates/finalizers
  verbs:
  - update
- apiGroups:
  - node.waok8s.github.io
  resources:
  - nodeconfigs/status
  - nodeconfigtemplates/status
  verbs:
  - get
  - patch
  - update
