# NOTE: This file is copied from MLMM repository.
# Important: Run "go generate ./..." to regenerate code after modifying this file.
openapi: 3.0.3
info:
  title: NEDO Machine Learning Model Management API
  description: |-
    This is NEDO Machine Learning Model Management API
  version: 0.1.0
paths:
  /redfish/v1/Systems/{systemId}:
    get:
      summary: Get system resource.
      description: |-
        Get system resource data of the BMC with path of the machine learning model resource added.<br>
        Only the path of the machine learning model resource to be added is listed in the response below.
      parameters:
        - in: path
          name: systemId
          schema:
            type: string
          required: true
          description: system ID
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/System"
        "500":
          description: internal error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalError"
  /redfish/v1/Systems/{systemId}/MachineLearningModel:
    get:
      summary: Get machine learning model resource.
      description: |-
        Get machine learning model resource containing
        power consumption model information and response time model information.
      parameters:
        - in: path
          name: systemId
          schema:
            type: string
          required: true
          description: system ID
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MachineLearningModel"
        "500":
          description: internal error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalError"
components:
  schemas:
    System:
      type: object
      properties:
        MachineLearningModel:
          type: object
          properties:
            "@odata.id":
              type: string
              example: /redfish/v1/Systems/1/MachineLearningModel
              description: Path of the machine learning model resource
    MachineLearningModel:
      type: object
      properties:
        "@odata.id":
          type: string
          example: "/redfish/v1/Systems/System.Embedded.1/MachineLearningModel"
          description: ID of resource
        "@odata.type":
          type: string
          example: "#MachineLearningModel.v1_0_0.MachineLearningModel"
          description: Type of resource
        "@odata.context":
          type: string
          example: "/redfish/v1/$metadata#Systems/System.Embedded.1/MachineLearningModel"
          description: Context URL of resource
        Name:
          type: string
          example: Machine Learning Model
          description: Resource name
        PowerConsumptionModel:
          type: object
          properties:
            Name:
              type: string
              example: hoge-pc-01
              description: Name of power consumption model
            Url:
              type: string
              example: http://10.0.0.20/model/hoge-pc-01
              description: URL of power consumption model
        ResponseTimeModel:
          type: object
          properties:
            Name:
              type: string
              example: hoge-pc-01
              description: Name of response time model
            Url:
              type: string
              example: http://10.0.0.20/model/hoge-rt-01
              description: URL of response time model
    InternalError:
      type: object
      properties:
        error:
          properties:
            code:
              type: string
              example: ""
              description: message code
            message:
              type: string
              example: "See @Message.ExtendedInfo for more information"
              description: error message
            "@Message.ExtendedInfo":
              type: object
              properties:
                Message:
                  type: string
                  example: "Internal error occurred."
                  description: error message
