apiVersion: v1
kind: ServiceAccount
metadata:
  name: wao-loadbalancer
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wao-loadbalancer-as-kube-proxy
subjects:
- kind: ServiceAccount
  name: wao-loadbalancer
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:node-proxier
  apiGroup: rbac.authorization.k8s.io
# ---
# NOTE: same role in wao-scheduler
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: metrics-reader
# rules:
#   - apiGroups: ["metrics.k8s.io"]
#     resources: [pods, nodes]
#     verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wao-loadbalancer-as-metrics-reader
subjects:
- kind: ServiceAccount
  name: wao-loadbalancer
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: metrics-reader
  apiGroup: rbac.authorization.k8s.io
# ---
# # NOTE: same role in wao-scheduler
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: custom-metrics-server-resources
# rules:
# - apiGroups:
#   - custom.metrics.k8s.io
#   resources: ["*"]
#   verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wao-loadbalancer-as-custom-metrics-server-resources
subjects:
- kind: ServiceAccount
  name: wao-loadbalancer
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: custom-metrics-server-resources
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wao-loadbalancer-as-wao-nodeconfig-viewer-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wao-nodeconfig-viewer-role
subjects:
- kind: ServiceAccount
  name: wao-loadbalancer
  namespace: kube-system
# ---
# NOTE: same role in wao-metrics-adapter
# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   name: secret-reader
#   namespace: wao-system
# rules:
# - apiGroups: [""]
#   resources: ["secrets"]
#   verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wao-loadbalancer-as-secret-reader
  namespace: wao-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-reader
subjects:
- kind: ServiceAccount
  name: wao-loadbalancer
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-service-reader
rules:
  - apiGroups: [""]
    resources: [pods, services]
    verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wao-loadbalancer-as-pod-service-reader
subjects:
- kind: ServiceAccount
  name: wao-loadbalancer
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: pod-service-reader
  apiGroup: rbac.authorization.k8s.io