name: "[wao-scheduler] CI"
on:
  push:
    branches: [main, release-*]
  pull_request:
    branches: [main, release-*]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: wao-scheduler
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # git fetch --unshallow
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.work # go.mod or go.work
      - name: "test: unit tests"
        run: make test
      - name: "test: integration tests"
        run: ./test/reset-test-cluster.sh && ./test/run-tests.sh
